"""Train the GNN path ranker.

Run from the repository root::

    python -m ml.training.train_gnn

Five changes from the previous version, each fixing something the audit found:

1. **Ranking loss, not MSE.** The model's output value is never used — only
   ``argmin`` is. Regression accuracy on the cost was therefore irrelevant while
   the ordering, which is all that matters, went unmeasured. Training now
   optimises a pairwise margin loss and reports **top-1 accuracy** and **mean
   regret against the oracle**, which are the numbers that go in the README.

2. **A genuinely independent validation set.** Validation data used to be
   generated by continuing the *same simulator instance* — same topology, same
   seed, same base latencies, just later timesteps. The reported "72% val MSE
   reduction" was not evidence of generalisation. Validation now uses a
   different seed, and a held-out test set uses a third.

3. **Trained on the deployment topology.** Training ran at ``num_nodes=100``,
   which the old generator turned into a pure degree-2 ring with only two
   candidate paths per pair, while inference ran on a degree-4 25-node mesh.
   Both are now 25 nodes with matched degree.

4. **Best-checkpoint saving, early stopping, LR schedule, fixed seeds.** The old
   loop saved the last epoch regardless of validation performance.

5. **Mini-batched.** 3,000 samples x 60 epochs at batch size 1 was 180,000
   single-sample optimiser steps.
"""

from __future__ import annotations

import argparse
import json
import logging
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.optim as optim

from core.paths import candidate_paths
from core.qos import ALL_CLASSES, QOS_PROFILES, evaluate_path
from core.simulator import NetworkSimulator
from ml.architectures.gnn import GNNRouterModel
from ml.features import build_graph_tensors
from ml.model_registry import RESULTS_DIR, path_for

logger = logging.getLogger("train_gnn")

K_PATHS = 5
INFEASIBLE_PENALTY = 10.0


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------
def generate_dataset(
    seed: int, num_samples: int, num_nodes: int = 25, pairs_per_step: int = 5
) -> list[dict]:
    """Build samples from an independently seeded simulator.

    Each sample is one routing task: the graph tensors, the candidate paths, and
    the true QoS score of each candidate under a sampled traffic class. The
    target is what the model must learn to *rank*.
    """
    rng = random.Random(seed)
    simulator = NetworkSimulator(num_nodes=num_nodes, seed=seed)
    for _ in range(50):  # warm up so utilization is not at its initial draw
        simulator.step()

    dataset: list[dict] = []
    while len(dataset) < num_samples:
        state = simulator.step()
        nodes = list(state.nodes)

        for _ in range(pairs_per_step):
            src, dst = rng.sample(nodes, 2)
            paths = candidate_paths(state, src, dst, k=K_PATHS)
            if len(paths) < 2:  # nothing to rank
                continue

            profile = QOS_PROFILES[rng.choice(list(ALL_CLASSES))]
            targets = []
            for path in paths:
                evaluation = evaluate_path(state, path, profile)
                score = evaluation.score
                if not evaluation.feasible:
                    score += INFEASIBLE_PENALTY
                targets.append(score)

            x, edge_index, edge_attr, paths_idx, path_edges, path_feats = (
                build_graph_tensors(state, paths, src, dst, profile)
            )
            dataset.append(
                {
                    "x": x,
                    "edge_index": edge_index,
                    "edge_attr": edge_attr,
                    "paths": paths_idx,
                    "path_edges": path_edges,
                    "path_feats": path_feats,
                    "targets": torch.tensor(targets, dtype=torch.float32),
                }
            )
            if len(dataset) >= num_samples:
                break

    return dataset


# ---------------------------------------------------------------------------
# Objective and metrics
# ---------------------------------------------------------------------------
def ranking_loss(pred: torch.Tensor, target: torch.Tensor, margin: float = 0.05) -> torch.Tensor:
    """Pairwise margin loss over every ordered pair of candidates in a sample.

    Penalises the model whenever it ranks a worse path above a better one, by at
    least ``margin``. This is what "train the thing you actually use" means when
    the only use of the output is ``argmin``.
    """
    n = pred.shape[0]
    if n < 2:
        return pred.sum() * 0.0
    pi, pj = pred.unsqueeze(0), pred.unsqueeze(1)
    ti, tj = target.unsqueeze(0), target.unsqueeze(1)
    sign = torch.sign(tj - ti)  # +1 when j is worse than i
    violation = torch.relu(margin - sign * (pj - pi))
    mask = ~torch.eye(n, dtype=torch.bool, device=pred.device)
    return violation[mask].mean()


@torch.no_grad()
def evaluate(model: GNNRouterModel, data: list[dict]) -> dict[str, float]:
    """Top-1 accuracy and mean regret against the oracle over the candidate set."""
    model.eval()
    hits = 0
    regrets: list[float] = []
    losses: list[float] = []

    for sample in data:
        prediction = model(
            sample["x"],
            sample["edge_index"],
            sample["edge_attr"],
            sample["paths"],
            sample["path_edges"],
            sample["path_feats"],
        )
        target = sample["targets"]
        losses.append(float(ranking_loss(prediction, target)))
        chosen = int(torch.argmin(prediction))
        best = int(torch.argmin(target))
        hits += int(chosen == best)
        regrets.append(float(target[chosen] - target[best]))

    n = max(1, len(data))
    return {
        "top1_accuracy": hits / n,
        "mean_regret": float(np.mean(regrets)) if regrets else 0.0,
        "ranking_loss": float(np.mean(losses)) if losses else 0.0,
    }


def random_baseline(data: list[dict], seed: int = 0) -> dict[str, float]:
    """What picking a candidate uniformly at random achieves on the same data."""
    rng = random.Random(seed)
    hits = 0
    regrets: list[float] = []
    for sample in data:
        target = sample["targets"]
        chosen = rng.randrange(len(target))
        best = int(torch.argmin(target))
        hits += int(chosen == best)
        regrets.append(float(target[chosen] - target[best]))
    n = max(1, len(data))
    return {
        "top1_accuracy": hits / n,
        "mean_regret": float(np.mean(regrets)) if regrets else 0.0,
    }


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description="Train the GNN path ranker.")
    parser.add_argument("--epochs", type=int, default=40)
    parser.add_argument("--train-samples", type=int, default=2500)
    parser.add_argument("--val-samples", type=int, default=600)
    parser.add_argument("--test-samples", type=int, default=600)
    parser.add_argument("--hidden-dim", type=int, default=64)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--patience", type=int, default=8)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)-7s %(message)s", datefmt="%H:%M:%S"
    )
    # Each episode builds a fresh simulator, which logs its topology at INFO.
    # That is useful once and noise 10,000 times.
    logging.getLogger("core.simulator").setLevel(logging.WARNING)

    torch.manual_seed(args.seed)
    random.seed(args.seed)
    np.random.seed(args.seed)

    logger.info("Generating data from three independently seeded simulators...")
    train_data = generate_dataset(seed=args.seed, num_samples=args.train_samples)
    val_data = generate_dataset(seed=args.seed + 1000, num_samples=args.val_samples)
    test_data = generate_dataset(seed=args.seed + 2000, num_samples=args.test_samples)
    logger.info(
        "train=%d val=%d test=%d (separate seeds, so validation measures generalisation)",
        len(train_data),
        len(val_data),
        len(test_data),
    )

    model = GNNRouterModel(node_dim=3, edge_dim=4, hidden_dim=args.hidden_dim)
    logger.info("Model has %d trainable parameters", model.parameter_count())

    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, "max", patience=4, factor=0.5)

    chance = random_baseline(val_data, seed=args.seed)
    logger.info(
        "Random-guess floor on validation: top1=%.3f regret=%.4f",
        chance["top1_accuracy"],
        chance["mean_regret"],
    )

    best_accuracy = -1.0
    best_state: dict | None = None
    epochs_without_improvement = 0
    started = time.time()

    for epoch in range(1, args.epochs + 1):
        model.train()
        random.shuffle(train_data)
        epoch_loss = 0.0

        # Mini-batching by gradient accumulation: samples have different graph
        # shapes, so they cannot be stacked into one tensor without padding.
        optimizer.zero_grad()
        for index, sample in enumerate(train_data, start=1):
            prediction = model(
                sample["x"],
                sample["edge_index"],
                sample["edge_attr"],
                sample["paths"],
                sample["path_edges"],
                sample["path_feats"],
            )
            loss = ranking_loss(prediction, sample["targets"]) / args.batch_size
            loss.backward()
            epoch_loss += float(loss) * args.batch_size

            if index % args.batch_size == 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                optimizer.zero_grad()
        optimizer.step()
        optimizer.zero_grad()

        metrics = evaluate(model, val_data)
        scheduler.step(metrics["top1_accuracy"])

        if metrics["top1_accuracy"] > best_accuracy:
            best_accuracy = metrics["top1_accuracy"]
            best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
            epochs_without_improvement = 0
            marker = " *best*"
        else:
            epochs_without_improvement += 1
            marker = ""

        if epoch % 2 == 0 or epoch == 1 or marker:
            logger.info(
                "epoch %02d/%d  train_loss=%.4f  val_top1=%.3f  val_regret=%.4f%s",
                epoch,
                args.epochs,
                epoch_loss / max(1, len(train_data)),
                metrics["top1_accuracy"],
                metrics["mean_regret"],
                marker,
            )

        if epochs_without_improvement >= args.patience:
            logger.info("Early stopping: no improvement for %d epochs", args.patience)
            break

    elapsed = time.time() - started
    if best_state is not None:
        model.load_state_dict(best_state)

    test_metrics = evaluate(model, test_data)
    test_chance = random_baseline(test_data, seed=args.seed + 7)

    logger.info("Training finished in %.1fs", elapsed)
    logger.info(
        "HELD-OUT TEST  top1=%.3f (random %.3f)  regret=%.4f (random %.4f)",
        test_metrics["top1_accuracy"],
        test_chance["top1_accuracy"],
        test_metrics["mean_regret"],
        test_chance["mean_regret"],
    )

    if test_metrics["top1_accuracy"] <= test_chance["top1_accuracy"]:
        logger.warning(
            "The model does not beat random guessing on held-out data. That is a "
            "result, and it must be reported as one rather than shipped quietly."
        )

    destination = path_for("gnn")
    destination.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "state_dict": model.state_dict(),
            "node_dim": 3,
            "edge_dim": 4,
            "hidden_dim": args.hidden_dim,
        },
        destination,
    )
    logger.info("Saved best checkpoint to %s", destination)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    report = {
        "model": "gnn_router",
        "objective": "pairwise ranking (margin loss)",
        "seed": args.seed,
        "epochs_run": epoch,
        "train_samples": len(train_data),
        "val_samples": len(val_data),
        "test_samples": len(test_data),
        "validation_independent": True,
        "best_val_top1_accuracy": best_accuracy,
        "test": test_metrics,
        "random_baseline_test": test_chance,
        "beats_random": bool(
            test_metrics["top1_accuracy"] > test_chance["top1_accuracy"]
        ),
        "train_seconds": round(elapsed, 1),
        "parameters": model.parameter_count(),
    }
    (RESULTS_DIR / "gnn_evaluation.json").write_text(json.dumps(report, indent=2))
    logger.info("Wrote %s", RESULTS_DIR / "gnn_evaluation.json")


if __name__ == "__main__":
    main()
